version: "3.2"
services:
  ci:
    build: .
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PARALLEL_JOB
      - BUILDKITE_PARALLEL_JOB_COUNT
      - BUILDKITE_PULL_REQUEST
